MUSCLE (3.8) multiple sequence alignment


YALI0_B00572g-t26_1-p1      MKISHKLEKAHAADSTP--TFSFEFFVPKTSQGVNNLYDRMDRMYQLG-PQFIDITWNA-
CAWG_02614-T-p1             MKISEKLTQAHKGSNPPPATFSFEFFVPKTSQGVQNLYDRMDRMYDLN-PIFIDITWNA-
YGL125W                     MKITEKLEQHRQTSGKP--TYSFEYFVPKTTQGVQNLYDRMDRMYEASLPQFIDITWNAG
YPL023C                     ----MSIRDLYHARASP--FISLEFFPPKTELGTRNLMERMHRMTALD-PLFITVTWGA-
CAWG_06112-T-p1             ---MSTVAERIASLKPDEKFVSFEFFPPKTDSGFRNLLARLNRMSAFN-PLFVTVTWGA-
YALI0_B14465g-t26_1-p1      ---MSTITKLIAGLKPDEKFFSLEFFPPKTQNGMANFRARLARMAALK-PLFITITWGA-
                                 .: .            *:*:* ***  *  *:  *: **     * *: :**.* 

YALI0_B00572g-t26_1-p1      GGRLSNLTNEMVATAQSALGLETCMHLTCTGMPKQLVENALQSAFDGGCQNILALRGDPP
CAWG_02614-T-p1             GGRSSTLTNEMVYTAQSTLGLETCMHLTCTNMKVELIDEALEKAFKSGCQNILALRGDPP
YGL125W                     GGRLSHLSTDLVATAQSVLGLETCMHLTCTNMPISMIDDALENAYHSGCQNILALRGDPP
YPL023C                     GGTTAEKTLTLASLAQQTLNIPVCMHLTCTNTEKAIIDDALDRCYNAGIRNILALRGDPP
CAWG_06112-T-p1             GGSTSEKSLDLAATCQNEIGITTVLHLTCTNTNKEVIDQALSKAKAAGVRNILALRGDPP
YALI0_B14465g-t26_1-p1      GGSTAKKSLDIASECQS-MGLDVCLHLTCTNMDPALIDQALEAASKAGICNILALRGDPP
                            **  :  :  :.  .*. :.: . :*****.    ::::**. .  .*  **********

YALI0_B00572g-t26_1-p1      VESEKWEAVDGG--FRYAKDLVKYIKSKYGDYFDIGVAAYPEGTPEEPD----VDILID-
CAWG_02614-T-p1             LDG---SESTGD--FKYAKDLIKYIHEKYDNHFNIGVAGYPEGHPEE------EDEQKTL
YGL125W                     RDAENWTPVEGG--FQYAKDLIKYIKSKYGDHFAIGVAGYPECHPELPN----KDVKLDL
YPL023C                     IGEDWLDSQSNESPFKYAVDLVRYIKQSYGDKFCVGVAAYPEGHCEGEAEGHEQDPLKDL
CAWG_06112-T-p1             RTEEYWTPNC-D--FNGAVDLVKYIRENYGDYFCIGVAAYPEGHVDGSDTSS-QNPQRDI
YALI0_B14465g-t26_1-p1      RGEEYWQPASPE--FQHAADLVKYIKKKHGNKFCVGVAGYPEGHVDGSDASH-QDFHHDL
                                          *. * **:.**...:.: * :***.***   :        :     

YALI0_B00572g-t26_1-p1      -HLKEKVDAGGTFIVTQMFYDTDNFLKWVDKCRAKGI---NVPIIPGIMPISTYASFMRR
CAWG_02614-T-p1             RYLKEKCDAGADFIITQMFYDVDNFISWCSKLRKIGV---DIPIIPGIMPISTYAAFIRR
YGL125W                     EYLKQKIDAGGDFIITQMFYDVDNFINWCSQVRAAGM---DVPIIPGIMPITTYAAFLRR
YPL023C                     VYLKEKVEAGADFVITQLFYDVEKFLTFEMLFRERIS--QDLPLFPGLMPINSYLLFHRA
CAWG_06112-T-p1             PFLVEKVKAGADFIITQLFFDVEKFIAFDKLLKEHDE-LKGIPLIPGLMPITTYKVFNRA
YALI0_B14465g-t26_1-p1      PYLKEKVEAGADFIITQMFYDDNKFLEYNKAVREFSPLLKNITIIPGLMPINTYTSFVRA
                             .* :* .**. *::**:*:* ::*: :    .       .:.::**:***.:*  * * 

YALI0_B00572g-t26_1-p1      ANWCQIQIPQDFLDQLEPV-KDDDMRVRELGTQLVADMCQKM--LDSGKIKHLHFYTMNL
CAWG_02614-T-p1             AKWSEIAIPQHFLDALDPI-KDDDFLVRERGTELVSEMCNKL--LQSGYVNHLHFYTMNL
YGL125W                     AQWGQISIPQHFSSRLDPI-KDDDELVRDIGTNLIVEMCQKL--LDSGYVSHLHIYTMNL
YPL023C                     AKLSHASIPPAILSRFPPEIQSDDNAVKSIGVDILIELIQEIYQRTSGRIKGFHFYTLNL
CAWG_06112-T-p1             AKLSHASIPKEILKQVDQV-CHDDNAVKALGVDILSEMIDQI--DKSTTIKGYHFYTLNL
YALI0_B14465g-t26_1-p1      ARLSHASVPPAILDRIQAVPTGNDQQVKDIGVEVVSDIVNDVYTKTNKTVRGFHFYTLNL
                            *.     :*  : . .      :*  *.  *.::: :: :.:    .  :   *:**:**

YALI0_B00572g-t26_1-p1      EKATVMVLERLNLP----------------------------------------------
CAWG_02614-T-p1             EKATVMILEKLNLI----------------------------------------------
YGL125W                     EKAPLMILERLNIL----------------------------------------------
YPL023C                     EKAIAQIVSQSPVLSHIVNESSEEEGEDETSGEIGSIENVPIEDADGDIVLDDSNEETVA
CAWG_06112-T-p1             EKAVASILDKSDVLRQVLEGSSYATRFEDAVASDSDDEDEPEKASERDITLTKT------
YALI0_B14465g-t26_1-p1      ERSVARILERSGFL--------------------TIEEDCAVEEATGSTASTTPNKT---
                            *.:   ::..  .                                               

YALI0_B00572g-t26_1-p1      ------AQDSAVAPLPWRPSLALG--R---------QDETVRPI-FWKNRKQSYVARTQD
CAWG_02614-T-p1             -EAIKSHDVVGGSELPWRKSLHPE--R---------SKESIRPI-FWQHRKYSYISRTAT
YGL125W                     -PTESEFNAHPLAVLPWRKSLNPK--R---------KNEEVRPI-FWKRRPYSYVARTSQ
YPL023C                     NRKRRRHSSLDSAKLIFNRAIVTE--KGLRYNNENGSMPSKKAL-ISISKGHGTLGRDAT
CAWG_06112-T-p1             -IKPRRVSSINDNELTSSKALVGK--A---------LLNDKKVL-VDISTGKGALGKDAI
YALI0_B14465g-t26_1-p1      -PLRRRSSATHRNRVVDDARHHPDAPK---------EEPDLTTLALAIASGEGAVGREAV
                                   .      :                            : .      . :..   

YALI0_B00572g-t26_1-p1      W--DEFPNGRWGDSRSPAFGELETYG-VLLRQSPQKVLELWGEPKTVDDLKTLLVNYLNG
CAWG_02614-T-p1             W--DEFPNGRWGDSRSPAFGDIDLCASELLRQSPKKAFELWGLPQSLAELSGIIINYLKG
YGL125W                     WAVDEFPNGRFGDSSSPAFGDLDLCGSDLIRQSANKCLELWSTPTSINDVAFLVINYLNG
YPL023C                     W--DEFPNGRFGDSRSPAYGEIDGYGPSIKV-SKSKALELWGIPKTIGDLKDIFIKYLEG
CAWG_06112-T-p1             W--DDFPNGRFGDSNSPAYGEIDGYGPTLKIHTPAEASTKWGTPESIADLTQVFINYLSG
YALI0_B14465g-t26_1-p1      W--DDFPNGRFGDSSSPAFGEIDGYGPSIHV-PPARALELWGYPVDDADLSKLFADTIVG
                            *  *:*****:*** ***:*:::  .  :   .       *. *    ::  :. . : *

YALI0_B00572g-t26_1-p1      KLASLPWSDVPISNEIETIKPQILELNNRGILTINSQPAVNGAKSTHPVHGWGPKNGYVY
CAWG_02614-T-p1             DLKSLPWSDGPVGDDTKVIVDDLIYLNQHGFFTMNSQPALNAVKSSEKVFGWGPKNGYVY
YGL125W                     NLKCLPWSDIPINDEINPIKAHLIELNQHSIITINSQPQVNGIRSNDKIHGWGPKDGYVY
YPL023C                     STDAIPWSDLGLSAETALIQEELIQLNYRGYLTLASQPATNATLSSDKIFGWGPAKGRLY
CAWG_06112-T-p1             KVDVVPWADSSLSPETALIQEELFQLNEKGWFSVASQPAVNGCKSTDNIFGWGPRNGIIY
YALI0_B14465g-t26_1-p1      KLPFMPWSDQTLSPETMLIQEQLMELNQKGIWTVASQPACNALKSDDNIFGWGPKGGYVF
                            .   :**:*  :. :   *   :: ** ..  :: ***  *.  *   :.****  * ::

YALI0_B00572g-t26_1-p1      QKAYLELLVTPEVAE-KLVKKLE---------NQSEITFYAVNKTGNLQTNAP------G
CAWG_02614-T-p1             QKQYLEFFCHKDVVS-KLLDHVEEFNVKGAESSSAFISYYAVDKDGNLSTNCK-----DD
YGL125W                     QKQYLEFMLPKTKLP-KLIDTLK---------NNEFLTYFAIDSQGDLLSNHP----DNS
YPL023C                     QKAFVEMFIHRQQWETTLKPKLDHY-------GRRKFSYYAGDSSGSFETNLD-----PH
CAWG_06112-T-p1             QKSFIELFMPKEDWK-KLLLKIE---------LDKTVTYYVGNKDGEIKSNLPIGPNVKL
YALI0_B14465g-t26_1-p1      QKSFAEFFISPEQWK-KLKPLLDA--------QEDLVSYYVAKSDKLVDTNVS-----ER
                            ** : *::        .*   :.             .:::. ..   . :*         

YALI0_B00572g-t26_1-p1      GPNAVTWGIYPGKEVIQPTIVEKISFLAWKEEAFRLGSEWAKCYPAE---------SESR
CAWG_02614-T-p1             DINAVTWGVFPGEEILQPTIVEKTSFLAWKDEVYRLFTEWAKIASSNLVEANQTQVDEFV
YGL125W                     KSNAVTWGIFPGREILQPTIVEKISFLAWKEEFYHILNEWKLNMNKY-------DKPHSA
YPL023C                     SSSVVTWGVFPNSPVKQTTIIEEESFKAWRDEAFSIWSEWAKLFPRN---------TPAN
CAWG_06112-T-p1             SKNAVTWGVFPSKEVVQPTVIDYESFKAWNEEAFLLWLEWARCYKKN---------SKSF
YALI0_B14465g-t26_1-p1      ASNGVTWGVFPNREIVQTTIIQEDSFDAWREEAFSIWSEWRALYKKN---------TASF
                              . ****::*.  : *.*:::  ** **.:* : :  **                    

YALI0_B00572g-t26_1-p1      KFLDDIFNNWYLVNIVHNDFHDSTG-IFDLFSDL------
CAWG_02614-T-p1             QLMKKFGDEFVLCNLVNNDFVDGNSTLFDLIKRLNIDDLN
YGL125W                     QFIQSLIDDYCLVNIVDNDYISPDDQIHSILLSL------
YPL023C                     ILLRLVHKDYCLVSIVHHDFKETDE-LWEMLLDQA-----
CAWG_06112-T-p1             ELLNSIYENYVLVSMIHHDFINENA-LWDLLLDE------
YALI0_B14465g-t26_1-p1      KLLDKIINEYLLVTVIHHDYVEEDG-LWELLGSV------
                             ::  . .:: * .:: :*: .    : .::         
